server:
  port: ${PORT:8080}

spring:
  application:
    name: spotifysync
  datasource:
    url: jdbc:h2:mem:spotifysync;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

spotify:
  client-id: ${SPOTIFY_CLIENT_ID:9b55437048a848f2bb077f20f30ee53f}
  client-secret: ${SPOTIFY_CLIENT_SECRET:a12044789e054d16bef40b2307427bc9}
  redirect-uri: ${SPOTIFY_REDIRECT_URI:https://spotisync.dpdns.org/api/auth/callback}
  scopes: playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-library-read,user-library-modify
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
